export enum GENRES {
  SCI_FI = 'SCI_FI',
  ROMANCE = 'ROMANCE',
}

export enum MOOD {
  CHEERFUL = 'CHEERFUL',
  REFLECTIVE = 'REFLECTIVE',
  GLOOMY = 'GLOOMY',
  HUMOROUS = 'HUMOROUS',
  MELANCHOLY = 'MELANCHOLY',
  IDYLLIC = 'IDYLLIC',
  WHIMSICAL = 'WHIMSICAL',
}

export enum PHRASE {
  READY_TO_USE = 'READY_TO_USE',
}

export enum WORD {
  RARE_DESCRIPTIVE = 'RARE_DESCRIPTIVE',
}
