export enum MOOD {
  CHEERFUL = 'CHEERFUL',
  REFLECTIVE = 'REFLECTIVE',
  GLOOMY = 'GLOOMY',
  HUMOROUS = 'HUMOROUS',
  MELANCHOLY = 'MELANCHOLY',
  IDYLLIC = 'IDYLLIC',
  WHIMSICAL = 'WHIMSICAL',
  ROMANTIC = 'ROMANTIC',
  MYSTERIOUS = 'MYSTERIOUS',
  OMINOUS = 'OMINOUS',
  CALM = 'CALM',
  LIGHTHEARTED = 'LIGHTHEARTED',
  HOPEFUL = 'HOPEFUL',
  ANGRY = 'ANGRY',
  FEARFUL = 'FEARFUL',
  TENSE = 'TENSE',
  LONELY = 'LONELY',
}

export enum PHRASE {
  READY_TO_USE = 'READY_TO_USE',
  ANALOGY = 'ANALOGY',
  FOOD_DESCRIPTION = 'FOOD_DESCRIPTION',
  BUILDINGS_DESCRIPTION = 'BUILDINGS_DESCRIPTION',
  BUILDINGS_INTERIOR_DESCRIPTION = 'BUILDINGS_INTERIOR_DESCRIPTION',
  CLOTHING_DESCRIPTION = 'CLOTHING_DESCRIPTION',
  HAIR_DESCRIPTION = 'HAIR_DESCRIPTION',
  MOOD_DESCRIPTION = 'MOOD_DESCRIPTION',
  POWER_DESCRIPTION = 'POWER_DESCRIPTION',
  PERSONALITY_DESCRIPTION = 'PERSONALITY_DESCRIPTION',
  PERSON_DESCRIPTION = 'PERSON_DESCRIPTION',
  ANIMAL_DESCRIPTION = 'ANIMAL_DESCRIPTION',
  CREATURE_DESCRIPTION = 'CREATURE_DESCRIPTION',
}

export enum WORD {
  RARE_DESCRIPTIVE = 'RARE_DESCRIPTIVE',
}
