# versão do docker compose
version: '3.7'

services:
  swriter_database:
    image: mysql
    container_name: swriter_database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=swriter
      - MYSQL_USER=root

    volumes:
      - pgdata:/data/mysql
#   app:
#     build: .
#     container_name: rentx
#     ports:
#       - 3333:3333
#     volumes:
#       - .:/usr/app
#     links:
#       - database_ignite
#     depends_on:
#       - database_ignite

volumes:
  pgdata:
    driver: local
