# versão do docker compose
version: '3.7'

services:
  swriter_database:
    image: mysql
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    container_name: swriter_database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=swriter

    volumes:
      - pgdata:/data/mysql
  app:
    build: .
    container_name: swriter_app
    ports:
      - 8090:8090
    volumes:
      - .:/usr/app
    links:
      - swriter_database
    depends_on:
      - swriter_database

volumes:
  pgdata:
    driver: local
